### ISSUE TITLE
Error when launching the plugin

### ISSUE THREAD

**Issue by varrieta** [3nids/wincan2qgep#1]
Hi,

I'm getting the following error when launching the plugin:

IOError: [Errno 22] invalid mode ('rb') or filename: '/var/run/user/1000/gvfs/smb-share:server=s4laveyre.sige.ch,share=inspection_tv/SIGE_2014/Rapport 2014/SIGE 5004B 14/XML/Project.xml' 
Traceback (most recent call last):
  File "C:/Users/valentine.arrieta/.qgis2/python/plugins\wincan2qgep\wincan2qgep_plugin.py", line 119, in openInspection
    data = ImportData(filepath).data
  File "C:/Users/valentine.arrieta/.qgis2/python/plugins\wincan2qgep\core\import_data.py", line 42, in **init**
    tree = ET.parse(filepath)
  File "C:\OSGEO4~1\apps\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\OSGEO4~1\apps\Python27\lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 22] invalid mode ('rb') or filename: '/var/run/user/1000/gvfs/smb-share:server=s4laveyre.sige.ch,share=inspection_tv/SIGE_2014/Rapport 2014/SIGE 5004B 14/XML/Project.xml'

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.16.0-Nødebo Nødebo, eb2c634

**Comment by 3nids** [comment]
the plugin only works locally for now, will try to update this asap.
